include:
  # auto devops build
  - template: 'Jobs/Build.gitlab-ci.yml'


stages:
  - build

.build-deb:
  image: "${IMAGE}"
  before_script:
    - apt-get -qq update
    - apt-get install -qq -y python3 python3-dev python3-pip python-is-python3
    - apt-get install -qq -y build-essential fakeroot devscripts
    - apt-get install -qq -y  debhelper dh-python python3-all-dev
  script:
    - make debian-build
    - mkdir "build-${IMAGE}"
    - mv ../cgwebpy*.deb "build-${IMAGE}/"
  artifacts:
    paths:
      - "build-${IMAGE}"

# build-ubuntu-22.04
run-build-ubuntu-22.04:
  stage: build
  extends: .build-deb
  variables:
    IMAGE: "ubuntu:22.04"


# build-debian-stable
run-build-debian-stable:
  stage: build
  extends: .build-deb
  variables:
    IMAGE: "debian:stable"
