stages:
  - build-ubuntu-22.04
  - build-debian-stable

# build-ubuntu-22.04
run-build-ubuntu-22.04:
  stage: build-ubuntu-22.04
  image: ubuntu:22.04
  before_script:
    - apt-get -qq update
    - apt-get install -qq -y python3 python3-dev python3-pip python-is-python3
    - apt-get install -qq -y build-essential fakeroot devscripts
    - apt-get install -qq -y  debhelper dh-python python3-all-dev
  script:
    - make debian-build
    - mkdir build-ubuntu-22.04
    - mv ../cgwebpy*.deb build-ubuntu-22.04/
  artifacts:
    paths:
      - build-ubuntu-22.04

# build-debian-stable
run-build-debian-stable:
  stage: build-debian-stable
  image: debian:stable
  before_script:
    - apt-get -qq update
    - apt-get install -qq -y python3 python3-dev python3-pip python-is-python3
    - apt-get install -qq -y build-essential fakeroot devscripts
    - apt-get install -qq -y  debhelper dh-python python3-all-dev
  script:
    - make debian-build
    - mkdir build-debian-stable
    - mv ../cgwebpy*.deb build-debian-stable/
  artifacts:
    paths:
      - build-debian-stable