
name: Debian package

on:
  push:
    tags:
      - '*'
jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -qq -y python3 python3-dev python3-pip python-is-python3
        sudo apt-get install -qq -y build-essential fakeroot devscripts
        sudo apt-get install -qq -y  debhelper dh-python python3-all-dev dh-exec
    - name: build package
      run: |
        make debian-build
        mkdir package
        for f in ../cgwebpy*.deb ; do mv "$f" "package/${{ matrix.os }}_$(basename "$f")" ; done
        echo "deb_package_file=$(ls package/*.deb)" >> $GITHUB_ENV
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-deb
        path: ${{ env.deb_package_file }}
    - name: create release
      id: create_release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.deb_package_file }}
        draft: false
        prerelease: false
